export const TYPES = {
  INIT: "[GET_STOCK]",
  UPDATE_STOCK: "[UPDATE_STOCK]",
  GET_CART_FROM_STORAGE: "[GET_CART]",
  ADD_PRODUCT: "[ADD PRODUCT]",
  REMOVE_ONE_FROM_CART: "[REMOVE_ONE_FROM_CART]",
  REMOVE_ALL_FROM_CART: "[REMOVE_ALL_FROM_CART]",
  CLEAR_CART: "[CLEAR_CART]",
};
