export const TYPES = {
  INIT: "[INIT]",
  SUCCES: "[SUCCED]",
  ERROR: "[ERROR]",
  GET_CART_FROM_STORAGE: "[GET_CART]",
  ADD_PRODUCT: "[ADD PRODUCT]",
  REMOVE_ONE_FROM_CART: "[REMOVE ONE FROM CART]",
  REMOVE_ALL_FROM_CART: "[REMOVE ALL FROM CART]",
  CLEAR_CART: "[CLEAR_CARD]"
};
